//! Operai Toolbox library.
//!
//! This crate provides the gRPC service implementation for the Operai Toolbox.

#[expect(
    clippy::doc_markdown,
    clippy::default_trait_access,
    clippy::missing_errors_doc,
    clippy::allow_attributes,
    clippy::allow_attributes_without_reason,
    reason = "generated by tonic-build"
)]
pub mod proto {
    include!("gen/brwse/toolbox/v1alpha1/brwse.toolbox.v1alpha1.rs");
}

pub mod builder;
pub mod runtime;
pub mod transports;

pub use builder::RuntimeBuilder;
pub use runtime::{CallMetadata, LocalRuntime, RemoteRuntime, Runtime};
pub use transports::grpc::ToolboxService;
#[cfg(feature = "mcp")]
pub use transports::mcp::{McpService, SearchEmbedFuture, SearchEmbedder};
